language: r
cache: packages
branches:
    only:
    - master
    - /^test.*$/
    - pkgdown
    
install: travis_wait 20 mvn install

r_github_packages:
    - jimhester/covr
    - IQSS/ZeligChoice
    - IQSS/ZeligEI

after_success:
    - Rscript -e 'covr::codecov()'
